# This is a basic workflow to help you get started with Actions

name: release-package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout tbl-build
        uses: actions/checkout@v4
        with:
          repository: leeyounho/tbl-build

      - name: debug1
        run: ls -al
        
      # Runs a single command using the runners shell
      - name: Run gradle
        run: gradle build

      - name: debug1
        run: ls -al
        
      # Runs a set of commands using the runners shell
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tbl-artifact
          path: tbl-build/build/distributions
